
server:
  port: 8080
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true


