spring:
  application:
    name: user-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka/}
