server:
  port: 8080

spring:
  application:
    name: bff

  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: bff-gateway
            client-secret: bff-gateway-secret
            authorization-grant-type: authorization_code
            redirect_uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - read
              - write
        provider:
          auth-server:
            issuer-uri: http://localhost:9000
    resourceserver:
       jwt:
         issuer-uri: http://localhost:9000
         jwk-set-uri: http://localhost:9000/oauth2/jwks

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

